### ISSUE TITLE
We need good test data for unit testing

### ISSUE THREAD

**Issue by dmlewis9** [dannyjacobs/ECHO#38]
I'll start by doing a few manual tests using the current datafiles, but we need to make a couple of small files to better allow comprehensive unit testing.

[ ] tlog
[ ] ulog
[ ] rx data
[ ] cst

**Comment by mickeyhorn** [comment]
The zip below contains tlog and ulog data trimmed down to the first few seconds to be below 50kB. They cover approximately the same amount of time, but at different step sizes, hence the difference in file size. It also contains an appropriate CST export model for the Chiropter at 70MHz.

I slacked David the rx data separately because it is in .hdf5 format, which is both too large for github and untrimmable (to my knowledge).
[Small_Test_Logs.zip](https://github.com/dannyjacobs/ECHO/files/5228264/Small_Test_Logs.zip)

**Comment by dmlewis9** [comment]
Appropriate data files added for testing. HDF5 data trimmed down to a manageable size.
